"""empty message

Revision ID: 006
Revises: 005_b
Create Date: 2025-11-09 08:52:12.534221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '006'
down_revision = '005_b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('user_profile', schema=None) as batch_op:
            batch_op.add_column(sa.Column('save_drafts', sa.Boolean(), nullable=True))
    except Exception:
        print("Migration unnecessary, skipping...")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_profile', schema=None) as batch_op:
        batch_op.drop_column('save_drafts')

    # ### end Alembic commands ###
