"""Make some corrections and simplifications to previous migrations

Revision ID: 008_a
Revises: 007
Create Date: 2025-11-10 04:04:11.758712

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '008_a'
down_revision = '007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('ds_download_record', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('ds_download_record_ibfk_1'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'data_set', ['dataset_id'], ['id'], ondelete='CASCADE')

        with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
            batch_op.drop_column('dataset_type')

        with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
            batch_op.drop_constraint(batch_op.f('ds_view_record_ibfk_1'), type_='foreignkey')
            batch_op.create_foreign_key(None, 'data_set', ['dataset_id'], ['id'], ondelete='CASCADE')

        with op.batch_alter_table('file', schema=None) as batch_op:
            batch_op.add_column(sa.Column('download_count', sa.Integer(), nullable=False))

        with op.batch_alter_table('user', schema=None) as batch_op:
            batch_op.alter_column('role',
                existing_type=mysql.VARCHAR(length=50),
                type_=sa.Enum('ADMIN', 'CURATOR', 'USER', name='userrole'),
                existing_nullable=True)
    except Exception:
        print("Migration unnecessary, skipping...")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'CURATOR', 'USER', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('file', schema=None) as batch_op:
        batch_op.drop_column('download_count')

    with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ds_view_record_ibfk_1'), 'data_set', ['dataset_id'], ['id'])

    with op.batch_alter_table('ds_meta_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dataset_type', mysql.VARCHAR(length=50), nullable=True))

    with op.batch_alter_table('ds_download_record', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ds_download_record_ibfk_1'), 'data_set', ['dataset_id'], ['id'])

    # ### end Alembic commands ###
