"""Add column draft_mode to data_set table

Revision ID: 012
Revises: 011
Create Date: 2025-12-06 20:34:39.051627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012'
down_revision = '011'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        with op.batch_alter_table('data_set', schema=None) as batch_op:
            batch_op.add_column(sa.Column('draft_mode', sa.Boolean(), nullable=False))
    except:
        print('Migration already applied, continuing to the next one')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('data_set', schema=None) as batch_op:
        batch_op.drop_column('draft_mode')

    # ### end Alembic commands ###
