"""015

Revision ID: 015
Revises: 014
Create Date: 2025-12-10 16:31:16.826508

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '015'
down_revision = '014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zenodo')
    with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('ds_view_record_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'data_set', ['dataset_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Enum('ADMIN', 'CURATOR', 'USER', name='userrole'),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('ADMIN', 'CURATOR', 'USER', name='userrole'),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    with op.batch_alter_table('ds_view_record', schema=None) as batch_op:
        batch_op.drop_constraint('ds_view_record_ibfk_3', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('ds_view_record_ibfk_1'), 'data_set', ['dataset_id'], ['id'])

    op.create_table('zenodo',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
