"""empty message

Revision ID: 988632bc400e
Revises: 006
Create Date: 2025-11-09 16:39:50.875509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988632bc400e'
down_revision = '006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fakenodo',
    sa.Column('dataset_id', sa.Integer(), nullable=False),
    sa.Column('associated_doi', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('dataset_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fakenodo')
    # ### end Alembic commands ###
